name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - front-experiment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: front-experiment  # Specify the branch to checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: "./Server Files/APoptimal-server"  # Quoted path
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Make sure the Node.js version matches your runtime in firebase.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_SERVER }}
        run: |
          firebase deploy --only hosting,functions
